log:
  level: info
pprof:
  enabled: false
  addr: "localhost:6060"
nats:
  url: "nats://localhost:4222"
  timeout: 2s
subscriber:
  stream: "ORDERS"
  subject: "orders.created"
  consumer: "notification_service"
  batch: 10
  timeout: 5s
  interval: 1s
  workers: 3
probes:
  livenessfilename: /tmp/live
  readinessfilename: /tmp/ready
  livenessinterval: 20s
shutdown:
  timeout: 5s
