server:
  port: 8080
  maxHeaderBytes: 1048576
  timeout:
    read: 10s
    write: 10s
    idle: 60s
    readHeader: 5s
database:
  url: "postgresql://user:password@localhost:5432/gocommerce"
log:
  level: info

