services:
  db:
    image: postgres:17.5-alpine
    restart: always
    container_name: postgres
    ports:
      - "${POSTGRES_PORT_HOST}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  product_migrator:
    build:
      context: .
      dockerfile: docker/migrator/Dockerfile
    image: migrator:0.1.0
    container_name: product-migrator
    environment:
      - MIGRATE_PATH=/migrations/product
      - MIGRATE_DB_URL=${PRODUCT_SVC_DATABASE_URL}
    volumes:
      - ./internal/product/store/migrations:/migrations/product
    networks:
      - ecommerce-network
    depends_on:
      db:
        condition: service_healthy

  product_service:
    build:
      context: .
      dockerfile: cmd/product_service/Dockerfile
      args:
        PRODUCT_SVC_DOCKER_IMAGE: ${PRODUCT_SVC_DOCKER_IMAGE}
        PRODUCT_SVC_DOCKER_TAG: ${PRODUCT_SVC_DOCKER_TAG}
    image: ${PRODUCT_SVC_DOCKER_IMAGE}:${PRODUCT_SVC_DOCKER_TAG}
    restart: unless-stopped
    container_name: product-service
    ports:
      - "${PRODUCT_SVC_HOST_PORT}:${PRODUCT_SVC_SERVER_PORT}"
      - "${PRODUCT_SVC_PPROF_HOST_PORT}:${PRODUCT_SVC_PPROF_PORT}"
      - "${PRODUCT_SVC_GRPC_HOST_PORT}:${PRODUCT_SVC_GRPC_PORT}"
    environment:
      - PRODUCT_SVC_SERVER_PORT=${PRODUCT_SVC_SERVER_PORT}
      - PRODUCT_SVC_DATABASE_URL=${PRODUCT_SVC_DATABASE_URL}
      - PRODUCT_SVC_LOG_LEVEL=${PRODUCT_SVC_LOG_LEVEL}
      - PRODUCT_SVC_SERVER_MAXHEADERBYTES=${PRODUCT_SVC_SERVER_MAXHEADERBYTES}
      - PRODUCT_SVC_SERVER_TIMEOUT_READ=${PRODUCT_SVC_SERVER_TIMEOUT_READ}
      - PRODUCT_SVC_SERVER_TIMEOUT_WRITE=${PRODUCT_SVC_SERVER_TIMEOUT_WRITE}
      - PRODUCT_SVC_SERVER_TIMEOUT_IDLE=${PRODUCT_SVC_SERVER_TIMEOUT_IDLE}
      - PRODUCT_SVC_SERVER_TIMEOUT_READHEADER=${PRODUCT_SVC_SERVER_TIMEOUT_READHEADER}
      - PRODUCT_SVC_PPROF_ENABLED=${PRODUCT_SVC_PPROF_ENABLED}
      - PRODUCT_SVC_PPROF_ADDR=${PRODUCT_SVC_PPROF_ADDR}
      - PRODUCT_SVC_GRPC_PORT=${PRODUCT_SVC_GRPC_PORT}
      - PRODUCT_SVC_GRPC_REFLECTION=${PRODUCT_SVC_GRPC_REFLECTION}
    networks:
      - ecommerce-network
    depends_on:
      db:
        condition: service_healthy
      product_migrator:
        condition: service_completed_successfully

volumes:
  postgres_data:
    name: postgres_data

networks:
  ecommerce-network:
    name: ecommerce-network
