server:
  port: 8080
  maxHeaderBytes: 1048576
  timeout:
    read: 10s
    write: 10s
    idle: 60s
    readHeader: 5s
database:
  host: localhost
  port: 5432
  user: user
  password: password
  name: products_db
  sslmode: disable
  timeout: 10s
log:
  level: info
pprof:
  enabled: false
  addr: "localhost:6060"
grpc:
  port: 50051
  reflection: false
telemetry:
  traces:
    otlphttp:
      endpoint: "jaeger:4318"
      insecure: true
      timeout: "2s"
shutdown:
  timeout: 5s
