server:
  port: 8080
  maxHeaderBytes: 1048576
  timeout:
    read: 10s
    write: 10s
    idle: 60s
    readHeader: 5s
database:
  url: "postgresql://user:password@localhost:5432/product_db?sslmode=disable"
  timeout: 10s
log:
  level: info
pprof:
  enabled: false
  addr: "localhost:6060"
grpc:
  port: 50051
  reflection: false
shutdown:
  timeout: 5s
