clusterName: gc-infra-pg
instances: 1
storage: 1Gi
users:
  - name: products_user
    database: products_db
  - name: orders_user
    database: orders_db
  - name: keycloak_user
    database: keycloak_db
