apiVersion: v1
kind: Service
metadata:
  name: {{ include "order.fullname" . }}
  labels:
    {{- include "order.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "order.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: {{ .Values.service.pprofPort }}
    targetPort: pprof
    protocol: TCP
    name: pprof
  {{- if .Values.metrics.enabled }}
  - port: {{ .Values.metrics.Port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  {{- end }}
