log:
  level: info
pprof:
  enabled: false
  addr: "localhost:6060"
grpc:
  port: 50051
  reflection: false
idp:
  url: http://keycloak:8080
  realm: gocommerce
  clientid: gocommerce-api
  secret: secret
telemetry:
  traces:
    otlphttp:
      endpoint: "jaeger:4318"
      insecure: true
      timeout: "2s"
shutdown:
  timeout: 5s
