server:
  port: 8080
  maxHeaderBytes: 1048576
  timeout:
    read: 11s
    write: 11s
    idle: 61s
    readHeader: 6s
log:
  level: info
pprof:
  enabled: false
  addr: "localhost:6060"
services:
  product:
    url: "http://product_service:8080"
    from: "/api/products"
    to: "/api/v1/products"
  order:
    url: "http://order_service:8080"
    from: "/api/orders"
    to: "/api/v1/orders"
  user:
    grpc:
      addr: user_service:50051
      timeout: 2s
    from: /api/auth/register
idp:
  jwksurl: http://keycloak:8080/realms/gocommerce/protocol/openid-connect/certs
  issuer: http://localhost:8181/realms/gocommerce
  clientid: gocommerce-api
  mininterval: 15m
shutdown:
  timeout: 5s
