replicaCount: 1

image:
  repository: order-service
  pullPolicy: IfNotPresent
  tag: "0.1.0"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: order-sa

podAnnotations: {}

podLabels:
  component: api
  team: backend

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  httpPort: 8080
  grpcPort: 50051
  pprofPort: 6060

metrics:
  enabled: true
  Host: ""
  Port: 9090

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 30

env:
  # Database Configuration
  ORDER_DB_HOST: gc-infra-pg-rw
  ORDER_DB_PORT: "5432"
  ORDER_DB_NAME: orders_db
  ORDER_DB_SSLMODE: disable
  ORDER_DB_TIMEOUT: "10s"

  # HTTP Configuration
  ORDER_SERVER_PORT: "8080"
  ORDER_SERVER_MAXHEADERBYTES: "1048576"
  ORDER_SERVER_TIMEOUT_READ: "10s"
  ORDER_SERVER_TIMEOUT_WRITE: "10s"
  ORDER_SERVER_TIMEOUT_IDLE: "60s"
  ORDER_SERVER_TIMEOUT_READHEADER: "5s"

  # Log Configuration
  ORDER_LOG_LEVEL: "info"

  # PProf Configuration
  ORDER_PPROF_ENABLED: "true"
  ORDER_PPROF_ADDR: ":6060"

  # gRPC Configuration
  ORDER_SERVICES_PRODUCT_GRPC_ADDR: "gc-app-product:50051"
  ORDER_SERVICES_PRODUCT_GRPC_TIMEOUT: "2s"

  # NATS Configuration
  ORDER_NATS_URL: "nats://gc-infra-nats:4222"
  ORDER_NATS_TIMEOUT: "2s"

  # Telemetry
  ORDER_TELEMETRY_TRACES_OTLPHTTP_ENDPOINT: jaeger-instance-collector.monitoring.svc.cluster.local:4318
  ORDER_TELEMETRY_TRACES_OTLPHTTP_INSECURE: true
  ORDER_TELEMETRY_TRACES_OTLPHTTP_TIMEOUT: 2s

  # Shutdown Configuration
  ORDER_SHUTDOWN_TIMEOUT: "5s"

envFromSecret:
  ORDER_DB_USER:
    name: gc-infra-pg-orders-user
    key: username
  ORDER_DB_PASSWORD:
    name: gc-infra-pg-orders-user
    key: password

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
