product:
  replicaCount: 1
  image:
    repository: product-service
    tag: "0.1.0"
  env:
    PRODUCT_DB_HOST: gc-infra-pg-rw
    PRODUCT_DB_NAME: products_db
    PRODUCT_TELEMETRY_TRACES_OTLPHTTP_ENDPOINT: jaeger-instance-collector.monitoring.svc.cluster.local:4318
  envFromSecret:
    PRODUCT_DB_USER:
      name: gc-infra-pg-products-user
      key: username
    PRODUCT_DB_PASSWORD:
      name: gc-infra-pg-products-user
      key: password

order:
  replicaCount: 1
  image:
    repository: order-service
    tag: "0.1.0"
  env:
    ORDER_DB_HOST: gc-infra-pg-rw
    ORDER_DB_NAME: orders_db
    ORDER_SERVICES_PRODUCT_GRPC_ADDR: "gc-app-product:50051"
    ORDER_NATS_URL: "nats://gc-infra-nats:4222"
    ORDER_TELEMETRY_TRACES_OTLPHTTP_ENDPOINT: jaeger-instance-collector.monitoring.svc.cluster.local:4318
  envFromSecret:
    ORDER_DB_USER:
      name: gc-infra-pg-orders-user
      key: username
    ORDER_DB_PASSWORD:
      name: gc-infra-pg-orders-user
      key: password

notification:
  replicaCount: 1
  image:
    repository: notification-service
    tag: "0.1.0"
  env:
    NOTIFICATION_NATS_URL: "nats://gc-infra-nats:4222"
    NOTIFICATION_TELEMETRY_TRACES_OTLPHTTP_ENDPOINT: jaeger-instance-collector.monitoring.svc.cluster.local:4318

user:
  replicaCount: 1
  image:
    repository: user-service
    tag: "0.1.0"
  init:
    img: busybox:1.37
    host: gc-infra-keycloakx-http
    port: 80
  env:
    USER_IDP_URL: http://gc-infra-keycloakx-http/auth
    USER_TELEMETRY_TRACES_OTLPHTTP_ENDPOINT: jaeger-instance-collector.monitoring.svc.cluster.local:4318
  envFromSecret:
    USER_IDP_SECRET:
      name: gc-infra-user-idp-secret
      key: secret

gateway:
  replicaCount: 1
  image:
    repository: api-gateway
    tag: "0.1.0"
  init:
    img: busybox:1.37
    host: gc-infra-keycloakx-http
    port: 80
  env:
    GW_SERVICES_PRODUCT_URL: http://gc-app-product:8080
    GW_SERVICES_ORDER_URL: http://gc-app-order:8080
    GW_SERVICES_USER_GRPC_ADDR: gc-app-user:50051
    GW_IDP_JWKSURL: http://gc-infra-keycloakx-http/auth/realms/gocommerce/protocol/openid-connect/certs
    GW_IDP_ISSUER: http://keycloak.127.0.0.1.nip.io/auth/realms/gocommerce
    GW_IDP_CLIENTID: gocommerce-api
    GW_TELEMETRY_TRACES_OTLPHTTP_ENDPOINT: jaeger-instance-collector.monitoring.svc.cluster.local:4318
