server:
  port: 8080
  maxHeaderBytes: 1048576
  timeout:
    read: 10s
    write: 10s
    idle: 60s
    readHeader: 5s
db:
  host: localhost
  port: 5432
  user: user
  password: password
  name: orders_db
  sslmode: disable
  timeout: 10s
log:
  level: info
pprof:
  enabled: false
  addr: "localhost:6060"
services:
  product:
    grpc:
      addr: "localhost:50051"
      timeout: 2s
nats:
  url: "nats://localhost:4222"
  timeout: 2s
telemetry:
  traces:
    otlphttp:
      endpoint: "jaeger:4318"
      insecure: true
      timeout: "2s"
shutdown:
  timeout: 5s
