###
# gRPC request to register a user
GRPC localhost:50052/user.v1.UserService/Register

{
  "userName": "jdoe5",
  "firstName": "John",
  "lastName": "Doe",
  "email": "jdoe5@example.com",
  "password": "password"
}

###

GRPC localhost:50051/grpc.health.v1.Health/Check

###
