{{- range .Values.users }}
{{- $secretName := (printf "%s-%s" $.Values.clusterName (.name | replace "_" "-")) }}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace $secretName) }}

{{- if not $secret }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ $.Values.clusterName }}-{{ .name | replace "_" "-" }}
  labels:
    cnpg.io/reload: "true"
data:
  username: {{ .name | b64enc }}
  password: {{ randAlphaNum 16 | b64enc }}

{{- end }}
{{- end }}
