apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-product-migrations
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  {{- (.Files.Glob "migrations/product_service/*.sql").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-order-migrations
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  {{- (.Files.Glob "migrations/order_service/*.sql").AsConfig | nindent 2 }}
