{{- range .Values.migrations }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-migrations
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  {{- $glob := printf "migrations/%s/*.sql" .name }}
  {{- ($.Files.Glob $glob).AsConfig | nindent 2 }}
---
{{- end }}
