// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	Price         int64      `json:"price"`
	StockQuantity int32      `json:"stock_quantity"`
	Version       int32      `json:"version"`
	CreatedAt     *time.Time `json:"created_at"`
}
