// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (Product, error)
	Delete(ctx context.Context, arg DeleteParams) (int64, error)
	FindAll(ctx context.Context, arg FindAllParams) ([]Product, error)
	FindByID(ctx context.Context, id uuid.UUID) (Product, error)
	FindByIDs(ctx context.Context, ids []uuid.UUID) ([]Product, error)
	Update(ctx context.Context, arg UpdateParams) (Product, error)
	UpdateStock(ctx context.Context, arg UpdateStockParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
