// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Status    string     `json:"status"`
	Version   int32      `json:"version"`
	CreatedAt *time.Time `json:"created_at"`
}

type OrderItem struct {
	ID           uuid.UUID  `json:"id"`
	OrderID      uuid.UUID  `json:"order_id"`
	ProductID    uuid.UUID  `json:"product_id"`
	Quantity     int32      `json:"quantity"`
	PricePerItem int64      `json:"price_per_item"`
	Price        int64      `json:"price"`
	Version      int32      `json:"version"`
	CreatedAt    *time.Time `json:"created_at"`
}
