// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	FindOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	FindOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	FindOrdersByUserID(ctx context.Context, arg FindOrdersByUserIDParams) ([]Order, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
