migrate_img: migrate/migrate:4
psql_img: alpine/psql:17.5
migrations:
  - name: order
    dbHost: gc-infra-pg-rw
    db: orders_db
    user: orders_user
    secret: gc-infra-pg-orders-user
  - name: product
    dbHost: gc-infra-pg-rw
    db: products_db
    user: products_user
    secret: gc-infra-pg-products-user
