name: Build and push images

on:
  workflow_call:
    inputs:
      modules:
        description: 'JSON array of modules to build'
        required: true
        type: string

jobs:
  build-and-push-images:
    name: Build & Push (${{ matrix.module }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(inputs.modules) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract and Sanitize Service Name and Commit SHA
        id: vars
        run: |
          BASE_NAME=$(basename ${{ matrix.module }})
          SERVICE_NAME=${BASE_NAME//_/-}
          echo "service_name=$SERVICE_NAME" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.module }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.vars.outputs.service_name }}:${{ steps.vars.outputs.sha_short }}
            ghcr.io/${{ github.repository_owner }}/${{ steps.vars.outputs.service_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
