# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: --timeout 3m
          
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
        cache: true
    - name: Build
      run: go build -v ./...
    - name: Unit & integration tests
      env:
        DOCKER_HOST: unix:///var/run/docker.sock
        TESTCONTAINERS_RYUK_DISABLED: "true"
      run: go test -race -v ./...
