name: Verify, build, lint, and test

on:
  workflow_call:
    inputs:
      modules:
        description: 'JSON array of modules to process'
        required: true
        type: string

jobs:
  verify_build_lint_test:
    name: (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(inputs.modules) }}
    steps:
      - uses: actions/checkout@v4

      - name: Read Go version from go.mod
        id: go-version
        working-directory: ${{ matrix.module }}
        run: |
          GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
          echo "version=$GO_VERSION" >> $GITHUB_OUTPUT
          echo "Using Go version: $GO_VERSION"

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go-version.outputs.version }}
          cache: true
          cache-dependency-path: |
            ${{ matrix.module }}/go.sum
            pkg/go.sum

      - name: Verify dependencies
        working-directory: ${{ matrix.module }}
        run: |
          go mod tidy

          files_to_check="go.mod"
          if [ -f go.sum ]; then
            files_to_check="$files_to_check go.sum"
          fi
          echo "Checking files: $files_to_check"
          if ! git diff --quiet --exit-code $files_to_check; then
            echo "❌ go.mod/go.sum not in sync. Run 'go mod tidy' and commit the changes."
            exit 1
          fi

          if grep -q "require" go.mod; then
            echo "Dependencies found, running 'go mod verify'..."
            go mod verify
          else
            echo "No dependencies found in go.mod, skipping 'go mod verify'."
          fi

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.1.0
          args: --timeout 15m
          working-directory: ${{ matrix.module }}
          skip-cache: false

      - name: Build
        working-directory: ${{ matrix.module }}
        run: go build -v ./...

      - name: Test with coverage
        working-directory: ${{ matrix.module }}
        run: |
          go test -race -v -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.module }}
          path: ${{ matrix.module }}/coverage.out
          if-no-files-found: ignore
